/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FreeEstimateRouteImport } from './routes/free-estimate'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSeamlessGutterInstallationRouteImport } from './routes/services.seamless-gutter-installation'
import { Route as ServicesGutterRepairRouteImport } from './routes/services.gutter-repair'
import { Route as ServicesGutterGuardsRouteImport } from './routes/services.gutter-guards'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const FreeEstimateRoute = FreeEstimateRouteImport.update({
  id: '/free-estimate',
  path: '/free-estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeamlessGutterInstallationRoute =
  ServicesSeamlessGutterInstallationRouteImport.update({
    id: '/services/seamless-gutter-installation',
    path: '/services/seamless-gutter-installation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesGutterRepairRoute = ServicesGutterRepairRouteImport.update({
  id: '/services/gutter-repair',
  path: '/services/gutter-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGutterGuardsRoute = ServicesGutterGuardsRouteImport.update({
  id: '/services/gutter-guards',
  path: '/services/gutter-guards',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/database': typeof DatabaseRoute
  '/estimate': typeof EstimateRoute
  '/estimator': typeof EstimatorRoute
  '/free-estimate': typeof FreeEstimateRoute
  '/services/gutter-guards': typeof ServicesGutterGuardsRoute
  '/services/gutter-repair': typeof ServicesGutterRepairRoute
  '/services/seamless-gutter-installation': typeof ServicesSeamlessGutterInstallationRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/database': typeof DatabaseRoute
  '/estimate': typeof EstimateRoute
  '/estimator': typeof EstimatorRoute
  '/free-estimate': typeof FreeEstimateRoute
  '/services/gutter-guards': typeof ServicesGutterGuardsRoute
  '/services/gutter-repair': typeof ServicesGutterRepairRoute
  '/services/seamless-gutter-installation': typeof ServicesSeamlessGutterInstallationRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/database': typeof DatabaseRoute
  '/estimate': typeof EstimateRoute
  '/estimator': typeof EstimatorRoute
  '/free-estimate': typeof FreeEstimateRoute
  '/services/gutter-guards': typeof ServicesGutterGuardsRoute
  '/services/gutter-repair': typeof ServicesGutterRepairRoute
  '/services/seamless-gutter-installation': typeof ServicesSeamlessGutterInstallationRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/database'
    | '/estimate'
    | '/estimator'
    | '/free-estimate'
    | '/services/gutter-guards'
    | '/services/gutter-repair'
    | '/services/seamless-gutter-installation'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/database'
    | '/estimate'
    | '/estimator'
    | '/free-estimate'
    | '/services/gutter-guards'
    | '/services/gutter-repair'
    | '/services/seamless-gutter-installation'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/database'
    | '/estimate'
    | '/estimator'
    | '/free-estimate'
    | '/services/gutter-guards'
    | '/services/gutter-repair'
    | '/services/seamless-gutter-installation'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DatabaseRoute: typeof DatabaseRoute
  EstimateRoute: typeof EstimateRoute
  EstimatorRoute: typeof EstimatorRoute
  FreeEstimateRoute: typeof FreeEstimateRoute
  ServicesGutterGuardsRoute: typeof ServicesGutterGuardsRoute
  ServicesGutterRepairRoute: typeof ServicesGutterRepairRoute
  ServicesSeamlessGutterInstallationRoute: typeof ServicesSeamlessGutterInstallationRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/free-estimate': {
      id: '/free-estimate'
      path: '/free-estimate'
      fullPath: '/free-estimate'
      preLoaderRoute: typeof FreeEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seamless-gutter-installation': {
      id: '/services/seamless-gutter-installation'
      path: '/services/seamless-gutter-installation'
      fullPath: '/services/seamless-gutter-installation'
      preLoaderRoute: typeof ServicesSeamlessGutterInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/gutter-repair': {
      id: '/services/gutter-repair'
      path: '/services/gutter-repair'
      fullPath: '/services/gutter-repair'
      preLoaderRoute: typeof ServicesGutterRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/gutter-guards': {
      id: '/services/gutter-guards'
      path: '/services/gutter-guards'
      fullPath: '/services/gutter-guards'
      preLoaderRoute: typeof ServicesGutterGuardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DatabaseRoute: DatabaseRoute,
  EstimateRoute: EstimateRoute,
  EstimatorRoute: EstimatorRoute,
  FreeEstimateRoute: FreeEstimateRoute,
  ServicesGutterGuardsRoute: ServicesGutterGuardsRoute,
  ServicesGutterRepairRoute: ServicesGutterRepairRoute,
  ServicesSeamlessGutterInstallationRoute:
    ServicesSeamlessGutterInstallationRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
